[package]
name = "perlin-noise"
version = "0.3.0"
authors = ["Ozaren <krishna.sd.2012@gmail.com>"]

[dependencies]
rand = "*"
num = "*"
typenum = "*"
linear-algebra = {path = "../linalg", version = "0.7.2", features = ['sized']}